export {default as Home} from "./Home"
export {default as MovieHub} from "./MovieHub"
export {default as MovieDetails} from "./ChannelDetails"
export {default as TvHub} from "./TvHub"
export {default as ChannelDetails} from "./ChannelDetails"
export {default as SeriesHub} from "./SeriesHub"
export {default as SerieDetails} from "./SerieDetails"